-- Unicelerate: Research impact (Leiden Ranking / OpenAlex)
--
-- One value per shared university, filled by seed_research_impact.sql
-- (generated by scripts/research-impact/build.mjs from the CWTS Leiden
-- Ranking Open Edition, CC0 1.0). Null means the university isn't in the
-- ranking, or its match hasn't been accepted: "not available".
--
-- Shape (see lib/types.ts, ResearchImpact):
--   { "overall": 87, "pp_top10": 0.152, "publications": 4279,
--     "fields": { "math_cs": 91, ... }, "ror": "04m5j1k67",
--     "source": "...", "source_url": "...", "data_year": "2020–2023",
--     "licence": "CC0 1.0", "checked_on": "2026-10-07" }
--
-- Safe to re-run.

alter table public.universities add column if not exists research_impact jsonb;

-- Every value says where it comes from, and only shared rows have one (a
-- student's own school can't claim a ranking value).
alter table public.universities drop constraint if exists universities_research_impact_check;
alter table public.universities add constraint universities_research_impact_check check (
  research_impact is null
  or (
    created_by is null
    and research_impact ? 'overall'
    and research_impact ? 'source'
    and research_impact ? 'data_year'
    and research_impact ? 'licence'
  )
);

-- Check (should list research_impact, jsonb):
--   select column_name, data_type from information_schema.columns
--   where table_schema = 'public' and table_name = 'universities' and column_name = 'research_impact';
