-- StudyCompass: College Scorecard import, part 0 of 6
-- Generated by scripts/scorecard/build-seed-sql.mjs from data/scorecard/universities.json.
-- Source: US Department of Education College Scorecard, data year 2024,
-- fetched 2026-10-06T06:55:42.188Z. Run after migration_007, files in order.

-- Their figures become official; their names and illustrative rankings stay.
update public.universities set scorecard_id = 166683
  where name = 'Massachusetts Institute of Technology' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 166027
  where name = 'Harvard University' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 243744
  where name = 'Stanford University' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 243780
  where name = 'Purdue University' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 228778
  where name = 'University of Texas at Austin' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 104151
  where name = 'Arizona State University' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 110635
  where name = 'University of California, Berkeley' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 110662
  where name = 'University of California, Los Angeles' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 170976
  where name = 'University of Michigan' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 139755
  where name = 'Georgia Institute of Technology' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 145637
  where name = 'University of Illinois Urbana-Champaign' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 236948
  where name = 'University of Washington' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 193900
  where name = 'New York University' and created_by is null and scorecard_id is null;
update public.universities set scorecard_id = 167358
  where name = 'Northeastern University' and created_by is null and scorecard_id is null;
