// Writes lib/exchange-rates.ts from the European Central Bank's euro
// foreign exchange reference rates: free, official, published every working
// day (https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html).
//
//   npm run data:fx
//
// The ECB publishes "1 EUR = x units" for about 30 currencies. A currency
// the ECB doesn't publish (e.g. TWD) is simply left out, so amounts in it
// show as "not available" in USD instead of being converted at a made-up
// rate. One exception, documented below: the UAE dirham is officially
// pegged to the US dollar.
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const ECB_URL = "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml";
const ECB_PAGE =
  "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html";

const xml = await (await fetch(ECB_URL)).text();
const date = /time=['"](\d{4}-\d{2}-\d{2})['"]/.exec(xml)?.[1];
const perEur = Object.fromEntries(
  [...xml.matchAll(/currency=['"]([A-Z]{3})['"]\s+rate=['"]([\d.]+)['"]/g)].map((m) => [m[1], Number(m[2])])
);
if (!date || !perEur.USD) throw new Error("Couldn't read the ECB file; nothing written.");
perEur.EUR = 1;

// US dollars per one unit of each currency: (USD per EUR) / (currency per EUR).
const usdPer = Object.fromEntries(
  Object.entries(perEur)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([code, rate]) => [code, Number((perEur.USD / rate).toPrecision(6))])
);

const file = `// GENERATED by scripts/fx/fetch-ecb.mjs (npm run data:fx). Don't edit by hand.
//
// US dollars per one unit of each currency, from the European Central Bank's
// euro reference rates of ${date}:
// ${ECB_PAGE}
// Converted amounts in the app are labeled "approximate, rate as of ${date}".
// Re-run the script to update; then regenerate the seed SQL that uses them.

export const RATES_DATE = "${date}";
export const RATES_SOURCE_URL = "${ECB_PAGE}";

export const USD_PER_UNIT: Record<string, number> = ${JSON.stringify(usdPer, null, 2)};

// The UAE dirham isn't in the ECB list, but it has been officially pegged at
// 3.6725 dirhams per US dollar since 1997 (Central Bank of the UAE).
USD_PER_UNIT.AED = Number((1 / 3.6725).toPrecision(6));

// Approximate US dollars for an amount in another currency, or null when we
// have no official rate for it (never a guess).
export function toUsd(amount: number | null | undefined, currency: string | null | undefined): number | null {
  if (amount === null || amount === undefined || !currency) return null;
  if (currency === "USD") return amount;
  const rate = USD_PER_UNIT[currency];
  return rate === undefined ? null : Math.round(amount * rate);
}
`;
writeFileSync(join(import.meta.dirname, "..", "..", "lib", "exchange-rates.ts"), file);
console.log(`Wrote lib/exchange-rates.ts: ${Object.keys(usdPer).length} currencies, ECB rates of ${date}`);
