-- StudyCompass: curated international universities — link existing sample rows
-- Generated by scripts/curated/build-international-sql.mjs from data/curated/.
-- Figures were checked by hand on each university's own website (URLs stored
-- with each row). Converted amounts use ECB rates of 2026-10-05.
-- Run after migration_011, files in order. Safe to re-run.

update public.universities set curated_id = 'oxford'
  where name = 'University of Oxford' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'cambridge'
  where name = 'University of Cambridge' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'imperial'
  where name = 'Imperial College London' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'ucl'
  where name = 'University College London' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'kcl'
  where name = 'King''s College London' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'edinburgh'
  where name = 'University of Edinburgh' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'manchester'
  where name = 'University of Manchester' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'utoronto'
  where name = 'University of Toronto' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'ubc'
  where name = 'University of British Columbia' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'mcgill'
  where name = 'McGill University' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'uwaterloo'
  where name = 'University of Waterloo' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'ualberta'
  where name = 'University of Alberta' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'unimelb'
  where name = 'University of Melbourne' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'usyd'
  where name = 'University of Sydney' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'anu'
  where name = 'Australian National University' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'monash'
  where name = 'Monash University' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'lmu'
  where name = 'LMU Munich' and created_by is null and curated_id is null and source = 'illustrative';
update public.universities set curated_id = 'tum'
  where name = 'Technical University of Munich' and created_by is null and curated_id is null and source = 'illustrative';
