-- Unicelerate: curated international universities — universities, part 02
-- Generated by scripts/curated/build-international-sql.mjs from data/curated/.
-- Figures were checked by hand on each university's own website (URLs stored
-- with each row). Converted amounts use ECB rates of 2026-10-05.
-- Run after migration_011, files in order. Safe to re-run.

insert into public.universities (curated_id, name, aliases, country, city, degree_levels, tuition, tuition_local, tuition_currency, tuition_basis, tuition_year, tuition_source_url, living_cost_per_year, living_cost_local, living_cost_currency, living_cost_source_url, fx_rate_date, acceptance_rate, acceptance_source_url, popular_programs, programs_source_url, coop_program, internship_support_url, source, source_url, data_year, fetched_at, description, is_featured, qs_ranking, program_rankings, avg_admitted_gpa, sat_25, sat_75, min_ielts)
values
  ('sapienza', 'Sapienza University of Rome', array['Sapienza', 'La Sapienza']::text[], 'Italy', 'Rome', array['Undergraduate', 'Masters', 'PhD']::text[], null, null, null, null, null, null, null, null, null, null, null, null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.uniroma1.it', '2026', '2026-10-06T00:00:00Z', 'University in Rome, Italy. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('ucd', 'University College Dublin', array['UCD']::text[], 'Ireland', 'Dublin', array['Undergraduate', 'Masters', 'PhD']::text[], null, null, null, null, null, null, null, null, null, null, null, null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.ucd.ie', '2026', '2026-10-06T00:00:00Z', 'University in Dublin, Ireland. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('tcd', 'Trinity College Dublin', array['Trinity', 'TCD']::text[], 'Ireland', 'Dublin', array['Undergraduate', 'Masters', 'PhD']::text[], null, null, null, null, null, null, null, null, null, null, null, null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.tcd.ie', '2026', '2026-10-06T00:00:00Z', 'University in Dublin, Ireland. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('univie', 'University of Vienna', array['Universität Wien', 'UniVie']::text[], 'Austria', 'Vienna', array['Undergraduate', 'Masters', 'PhD']::text[], null, null, null, null, null, null, null, null, null, null, null, null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.univie.ac.at', '2026', '2026-10-06T00:00:00Z', 'University in Vienna, Austria. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('tuwien', 'TU Wien', array['Vienna University of Technology', 'Technische Universität Wien']::text[], 'Austria', 'Vienna', array['Undergraduate', 'Masters', 'PhD']::text[], 1628, 1453.44, 'EUR', '€726.72 per semester × 2 for non-EU/EEA students', 'year not stated on the page (checked 2026-10-06)', 'https://www.tuwien.at/en/studies/admission/students-union-fee-and-tuition-fee/tuition-fee', null, null, null, null, '2026-10-05', null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.tuwien.at', '2026', '2026-10-06T00:00:00Z', 'University in Vienna, Austria. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('kuleuven', 'KU Leuven', array['Leuven', 'Katholieke Universiteit Leuven']::text[], 'Belgium', 'Leuven', array['Undergraduate', 'Masters', 'PhD']::text[], 10637, 9493.92, 'EUR', 'Non-EEA tuition for a full year of 60 credits (standard rate)', '2026-27', 'https://www.kuleuven.be/english/education/student/fees/tuition-fee-breakdown', null, null, null, null, '2026-10-05', null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.kuleuven.be', '2026-27', '2026-10-06T00:00:00Z', 'University in Leuven, Belgium. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('ugent', 'Ghent University', array['UGent', 'Universiteit Gent']::text[], 'Belgium', 'Ghent', array['Undergraduate', 'Masters', 'PhD']::text[], null, null, null, null, null, null, null, null, null, null, null, null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.ugent.be', '2026', '2026-10-06T00:00:00Z', 'University in Ghent, Belgium. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('ub', 'University of Barcelona', array['UB', 'Universitat de Barcelona']::text[], 'Spain', 'Barcelona', array['Undergraduate', 'Masters', 'PhD']::text[], null, null, null, null, null, null, null, null, null, null, null, null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://web.ub.edu', '2026', '2026-10-06T00:00:00Z', 'University in Barcelona, Spain. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('auckland', 'University of Auckland', array['UoA', 'Auckland']::text[], 'New Zealand', 'Auckland', array['Undergraduate', 'Masters', 'PhD']::text[], 23616, 42236.4, 'NZD', 'Annual international fee for the Bachelor of Arts (lowest listed group); other degrees cost more', '2027', 'https://www.auckland.ac.nz/en/study/fees-and-money-matters/tuition-fees/international-student-fees/undergraduate-international-fees.html', null, null, null, null, '2026-10-05', null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.auckland.ac.nz', '2027', '2026-10-06T00:00:00Z', 'University in Auckland, New Zealand. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('nyuad', 'NYU Abu Dhabi', array['NYUAD', 'New York University Abu Dhabi']::text[], 'United Arab Emirates', 'Abu Dhabi', array['Undergraduate', 'Masters', 'PhD']::text[], 68574, 68574, 'USD', 'Annual tuition (before financial aid, which NYUAD awards on need)', '2026-27', 'https://nyuad.nyu.edu/en/apply/undergraduate/scholarships-and-financial-aid/cost-of-attendance.html', null, null, null, null, null, null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://nyuad.nyu.edu', '2026-27', '2026-10-06T00:00:00Z', 'University in Abu Dhabi, United Arab Emirates. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null),
  ('khalifa', 'Khalifa University', array['KU Abu Dhabi', 'Khalifa University of Science and Technology']::text[], 'United Arab Emirates', 'Abu Dhabi', array['Undergraduate', 'Masters', 'PhD']::text[], null, null, null, null, null, null, null, null, null, null, null, null, null, '{}'::text[], null, 'unknown', null, 'curated', 'https://www.ku.ac.ae', '2026', '2026-10-06T00:00:00Z', 'University in Abu Dhabi, United Arab Emirates. Figures checked by hand on its own website; see Sources.', true, null, '{}'::jsonb, null, null, null, null)
on conflict (curated_id) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  country = excluded.country,
  city = excluded.city,
  degree_levels = excluded.degree_levels,
  tuition = excluded.tuition,
  tuition_local = excluded.tuition_local,
  tuition_currency = excluded.tuition_currency,
  tuition_basis = excluded.tuition_basis,
  tuition_year = excluded.tuition_year,
  tuition_source_url = excluded.tuition_source_url,
  living_cost_per_year = excluded.living_cost_per_year,
  living_cost_local = excluded.living_cost_local,
  living_cost_currency = excluded.living_cost_currency,
  living_cost_source_url = excluded.living_cost_source_url,
  fx_rate_date = excluded.fx_rate_date,
  acceptance_rate = excluded.acceptance_rate,
  acceptance_source_url = excluded.acceptance_source_url,
  popular_programs = excluded.popular_programs,
  programs_source_url = excluded.programs_source_url,
  coop_program = excluded.coop_program,
  internship_support_url = excluded.internship_support_url,
  source = excluded.source,
  source_url = excluded.source_url,
  data_year = excluded.data_year,
  fetched_at = excluded.fetched_at,
  description = excluded.description,
  is_featured = excluded.is_featured,
  qs_ranking = excluded.qs_ranking,
  program_rankings = excluded.program_rankings,
  avg_admitted_gpa = excluded.avg_admitted_gpa,
  sat_25 = excluded.sat_25,
  sat_75 = excluded.sat_75,
  min_ielts = excluded.min_ielts
where universities.created_by is null;
