-- StudyCompass: curated international universities — co-op programs
-- Generated by scripts/curated/build-international-sql.mjs from data/curated/.
-- Figures were checked by hand on each university's own website (URLs stored
-- with each row). Converted amounts use ECB rates of 2026-10-05.
-- Run after migration_011, files in order. Safe to re-run.

update public.universities set coop_program = 'mandatory', internship_support_url = 'https://drexel.edu/scdc/co-op/undergraduate/'
  where scorecard_id = 212054 and created_by is null; -- Drexel University
