-- Unicelerate: curated international universities — rankings
-- Generated by scripts/curated/build-international-sql.mjs from data/curated/.
-- Figures were checked by hand on each university's own website (URLs stored
-- with each row). Converted amounts use ECB rates of 2026-10-05.
-- Run after migration_011, files in order. Safe to re-run.

-- (none yet)
