-- Unicelerate: which shared universities are featured (shown by default).
-- Generated by scripts/build-featured-sql.mjs from the rule in
-- scripts/relevance-rule.mjs and data/curated/featured_us.csv. Don't edit by hand.
-- Rule: R1/R2 research OR SAT 75th percentile >= 1400 OR a known ranking
-- OR hand-curated; every non-Scorecard shared school is always featured.
-- Expected: 371 of 1577 College Scorecard schools (data year 2024).
-- Run after migration_010. Safe to re-run.

update public.universities set is_featured = coalesce(
  source <> 'College Scorecard'
  or research_intensity in ('very_high', 'high')
  or coalesce(sat_75, 0) >= 1400
  or qs_ranking is not null
  or scorecard_id = any(array[]::integer[]),
  false
)
where created_by is null;
