// Turns the cached raw Scorecard pages into data/scorecard/universities.json:
// one clean row per school, each with its source, data year and fetch time.
//
//   npm run data:normalize-scorecard
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { normalizeSchool } from "./normalize-lib.mjs";

const ROOT = join(import.meta.dirname, "..", "..");
const CACHE_DIR = join(ROOT, "ml", "data", "raw", "scorecard");
const OUT_DIR = join(ROOT, "data", "scorecard");

const meta = JSON.parse(readFileSync(join(CACHE_DIR, "meta.json"), "utf8"));
const raw = readdirSync(CACHE_DIR)
  .filter((f) => /^page-\d+\.json$/.test(f))
  .sort()
  .flatMap((f) => JSON.parse(readFileSync(join(CACHE_DIR, f), "utf8")));

const rows = [];
let skipped = 0;
for (const school of raw) {
  const row = normalizeSchool(school, { dataYear: meta.data_year, fetchedAt: meta.fetched_at });
  if (row) rows.push(row);
  else skipped++;
}
// Stable order, so a refresh only shows real changes in a diff.
rows.sort((a, b) => a.scorecard_id - b.scorecard_id);

const count = (key) => rows.filter((r) => r[key] !== null && !(Array.isArray(r[key]) && r[key].length === 0)).length;
const coverage = {
  schools: rows.length,
  skipped_no_tuition: skipped,
  with_sat_range: count("sat_25"),
  with_living_cost: count("living_cost_per_year"),
  with_programs: count("popular_programs"),
  with_median_earnings: count("median_earnings_10yr"),
  with_completion_rate: count("completion_rate"),
  with_retention_rate: count("retention_rate"),
  with_research_intensity: count("research_intensity"),
};

// Where a school's median earnings sit among all the imported schools. The
// "work experience" focus in lib/matching.ts scores earnings on this scale,
// so the cut-offs come from the data rather than being picked by hand.
function percentile(sorted, p) {
  const i = (sorted.length - 1) * p;
  const lo = Math.floor(i);
  const hi = Math.ceil(i);
  return Math.round(sorted[lo] + (sorted[hi] - sorted[lo]) * (i - lo));
}
const earnings = rows
  .map((r) => r.median_earnings_10yr)
  .filter((v) => typeof v === "number")
  .sort((a, b) => a - b);
const reference = {
  note: "Generated by scripts/scorecard/normalize.mjs. Percentiles of median earnings 10 years after entry across the imported schools.",
  source: "US Department of Education College Scorecard",
  data_year: meta.data_year,
  schools: earnings.length,
  median_earnings_10yr: {
    p10: percentile(earnings, 0.1),
    p50: percentile(earnings, 0.5),
    p90: percentile(earnings, 0.9),
  },
};

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  join(OUT_DIR, "universities.json"),
  JSON.stringify(
    {
      source: "US Department of Education College Scorecard (https://collegescorecard.ed.gov/)",
      data_year: meta.data_year,
      fetched_at: meta.fetched_at,
      filters: meta.filters,
      coverage,
      universities: rows,
    },
    null,
    1
  ) + "\n"
);

writeFileSync(
  join(ROOT, "lib", "scorecard-reference.json"),
  JSON.stringify(reference, null, 2) + "\n"
);

console.log(`Wrote ${rows.length} schools to data/scorecard/universities.json (data year ${meta.data_year})`);
console.log("Coverage:", JSON.stringify(coverage));
console.log("Wrote lib/scorecard-reference.json:", JSON.stringify(reference.median_earnings_10yr));
