// GENERATED by scripts/fx/fetch-ecb.mjs (npm run data:fx). Don't edit by hand.
//
// US dollars per one unit of each currency, from the European Central Bank's
// euro reference rates of 2026-10-05:
// https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
// Converted amounts in the app are labeled "approximate, rate as of 2026-10-05".
// Re-run the script to update; then regenerate the seed SQL that uses them.

export const RATES_DATE = "2026-10-05";
export const RATES_SOURCE_URL = "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html";

export const USD_PER_UNIT: Record<string, number> = {
  "AUD": 0.69603,
  "BRL": 0.200612,
  "CAD": 0.701609,
  "CHF": 1.20331,
  "CNY": 0.149152,
  "CZK": 0.0458129,
  "DKK": 0.149896,
  "EUR": 1.1204,
  "GBP": 1.32247,
  "HKD": 0.127427,
  "HUF": 0.00304622,
  "IDR": 0.0000558249,
  "ILS": 0.326552,
  "INR": 0.0103845,
  "ISK": 0.0081781,
  "JPY": 0.00631995,
  "KRW": 0.000744056,
  "MXN": 0.0550977,
  "MYR": 0.244677,
  "NOK": 0.104151,
  "NZD": 0.559138,
  "PHP": 0.0159558,
  "PLN": 0.255828,
  "RON": 0.209958,
  "SEK": 0.099569,
  "SGD": 0.781093,
  "THB": 0.0296779,
  "TRY": 0.020343,
  "USD": 1,
  "ZAR": 0.0601515
};

// The UAE dirham isn't in the ECB list, but it has been officially pegged at
// 3.6725 dirhams per US dollar since 1997 (Central Bank of the UAE).
USD_PER_UNIT.AED = Number((1 / 3.6725).toPrecision(6));

// Approximate US dollars for an amount in another currency, or null when we
// have no official rate for it (never a guess).
export function toUsd(amount: number | null | undefined, currency: string | null | undefined): number | null {
  if (amount === null || amount === undefined || !currency) return null;
  if (currency === "USD") return amount;
  const rate = USD_PER_UNIT[currency];
  return rate === undefined ? null : Math.round(amount * rate);
}
